name: 🚀 Deploy website on push

on:
  push:
    branches: [main]

jobs:
  web-deploy:
    name: 🎉 FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.ftp_dir}}

  install:
    name: Run compser install
    needs: [web-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SOP_HOST }}
          username: ${{ secrets.SOP_SSH_USERNAME }}
          password: ${{ secrets.SOP_SSH_PASSWORD }}
          port: ${{ secrets.SOP_SSH_PORT }}
          script: cd public_html/kame/gotmp && composer install
